name: Build Wrapper
on:
    push:
      branches:
        - master
    workflow_dispatch:
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: 🏗 Setup repo
          uses: actions/checkout@v3
  
        - name: 🏗 Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: node
            cache: npm
  
        - name: 🏗 Setup EAS
          uses: expo/expo-github-action@v8
          with:
            eas-version: latest
            token: ${{ secrets.EXPO_TOKEN }}
  
        - name: 📦 Install dependencies
          run: npm install
  
        - name: 🚀 Build app
          run: eas build --non-interactive --platform android --local

        - name: Find output
          run: find . -name "*.apk"

        - name: Upload to Release
          uses: softprops/action-gh-release@v1
          with:
              files: |
                android/*.apk
              #placeholder
              name: Wrapper-${{ github.run_id }}
              tag_name: ${{ github.run_id }}
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
